FROM node:18.15-bullseye-slim AS dev
WORKDIR /workspace
RUN apt update && apt install wget -y
RUN cd /tmp && wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb \
        && dpkg -i google-chrome-stable_current_amd64.deb \
        && apt install --fix-broken -y \
        && dpkg -i google-chrome-stable_current_amd64.deb \
        && rm -rf /tmp/*